[package]
name = "alloy-ethers-typecast"
version = "0.2.0"
edition = "2021"
description = "Crate for safe typecasting between ethers and alloy types"
license = "CAL-1.0"
homepage = "https://github.com/rainlanguage/rain.interpreter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.14", features = [
  "legacy",
  "ledger",
] }
alloy-primitives = { version = "0.6.3", features = ["rand"] }
alloy-sol-types = { version = "0.6.3" }
tracing = "0.1.37"
serde_json = "1.0.111"
derive_builder = "0.20.0"
async-trait = "0.1.77"
thiserror = "1.0.56"
tracing-subscriber = "0.3.18"
serde = "1.0.195"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["full"] }
anyhow = "1.0.70"

[lints.clippy]
all = "warn"

[package.metadata.docs.rs]
all-features = true
